import { ArrowRight, Check, CircleHelp, Compass, FileText, ShieldCheck, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { categories, guidance, trust } from '@/lib/mock-data';
import { Button } from './ui';
import { FeedbackForm } from './feedback-form';

export function Trust(){return <section className="border-y border-line bg-white py-8"><div className="container grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{trust.map(([t,d],i)=><article className="flex gap-3" key={t}><span className="text-sage">{[<ShieldCheck key="a" size={19}/>,<CircleHelp key="b" size={19}/>,<Compass key="c" size={19}/>,<Check key="d" size={19}/>][i]}</span><div><h3 className="text-sm font-bold">{t.replace('Source-backed','Source-aware').replace('Action-focused','Action-oriented').replace('Privacy-minded','Privacy-conscious')}</h3><p className="mt-1 text-xs leading-5 text-ink/60">{d.replace('See where your information comes from.','Guidance grounded in trusted information.').replace('Know what to do next, not just what the rules say.','Know what to do next.').replace('Designed with responsible handling of citizen information.','Your information is handled responsibly.')}</p></div></article>)}</div></section>}
export function How(){const steps=[['Tell us what happened','Describe your situation in your own words.'],['Understand your options','LokSeva organizes the relevant civic process.'],['See trusted information','Review the sources behind the guidance.'],['Take your next step','Generate an action plan or draft a request.']];return <section id="how" className="container py-24"><p className="eyebrow">How LokSeva Works</p><h2 className="display mt-3 text-4xl font-bold">From confusion to action.</h2><div className="mt-12 grid gap-4 md:grid-cols-4">{steps.map(([t,d],i)=><article className="card p-6 transition hover:-translate-y-1 hover:shadow-soft" key={t}><span className="text-sm font-bold text-sage">0{i+1}</span><h3 className="mt-7 font-bold text-sm">{t}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{d}</p></article>)}</div></section>}
export function Categories(){return <section id="help" className="bg-white py-24"><div className="container"><p className="eyebrow">Start here</p><h2 className="display mt-3 text-4xl font-bold">What can LokSeva help you with?</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=>{const Icon=c.icon;return <Link href={`/guidance?category=${c.key}`} key={c.key} aria-label={`Explore ${c.title}`} className="card group p-6 transition hover:-translate-y-1 hover:border-blue/40 hover:shadow-soft"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue/10 text-blue"><Icon size={20}/></span><h3 className="mt-6 font-bold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{c.description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-blue">Explore <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></Link>})}</div></div></section>}
export function Preview(){const plan=['Identify the responsible department','Collect relevant information','Submit the appropriate request','Keep the acknowledgement/reference number'];return <section className="container py-24"><div className="grid items-center gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Example guidance</p><h2 className="display mt-3 text-4xl font-bold">From confusion to a clear next step.</h2><p className="mt-5 text-ink/65 leading-7">A focused view brings together what we understand, what usually happens next and source material to review. This is an illustrative sample of how LokSeva structures civic guidance.</p></div><div className="rounded-[26px] border border-line bg-white p-5 shadow-soft sm:p-7"><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-wider text-sage">Example guidance</p><span className="text-xs text-ink/45">Prototype</span></div><p className="mt-3 font-semibold">What we understand</p><p className="mt-1 text-sm text-ink/60">You are looking for records related to a public road project.</p><div className="my-5 rounded-xl bg-mist p-4"><p className="text-sm font-bold">What usually happens next</p><p className="mt-2 text-sm text-ink/60">An information request may help you seek relevant project records from the responsible authority.</p></div><p className="text-xs font-bold uppercase tracking-wider text-sage">Action plan</p>{plan.map((x,i)=><div className="mt-3 flex gap-3 text-sm" key={x}><span className="font-bold text-sage">{i+1}.</span>{x}</div>)}<div className="mt-6 grid gap-2 sm:grid-cols-2">{guidance.sources.map(s=><div className="rounded-lg border border-line p-3 text-xs" key={s.title}><FileText size={14} className="mb-2 text-blue"/><b className="block">{s.title}</b><span className="mt-1 block text-ink/55">Demo source</span></div>)}</div></div></div></section>}
export function Why(){return <section className="bg-[#e7efe9] py-24"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">RTI assistant</p><h2 className="display mt-3 text-4xl font-bold">Turn a question into a clearer RTI draft.</h2><p className="mt-5 max-w-lg leading-7 text-ink/65">LokSeva can help organize the information you want to request into a structured draft.</p><Button href="/rti" className="mt-7">Explore RTI Generator</Button></div><article className="rounded-2xl bg-white p-7 shadow-soft"><p className="text-right text-xs text-ink/50">Date: [To be added]</p><p className="mt-6 text-sm">To,<br/>The Public Information Officer<br/>[Public Authority]</p><p className="mt-6 text-center text-sm font-bold">Subject: Request for information under the RTI Act, 2005</p><p className="mt-6 text-sm leading-7 text-ink/65">I request information concerning the local road project, including approved estimates, work order and current completion status.</p><p className="mt-7 text-sm">Yours faithfully,<br/>[Applicant details]</p></article></div></section>}
export function Feedback(){return <section className="bg-ink py-20 text-white"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#b8dac9]">Prototype feedback</p><h2 className="display mt-3 text-4xl font-bold">Help us improve LokSeva</h2><p className="mt-4 max-w-md leading-7 text-white/65">Your perspective helps shape a clearer civic guidance experience. Feedback is stored only in this browser for this prototype.</p></div><FeedbackForm/></div></section>}
export function Responsible(){const items=[['Clearer civic information','LokSeva is designed to make civic information easier to understand.'],['Visible sources','Sources should be visible where possible, so you can review the context.'],['Verify generated guidance','AI-generated information should be checked against official requirements.'],['Important limitation','LokSeva is not a substitute for professional legal advice.']];return <section className="container py-24"><p className="eyebrow">Responsible AI</p><h2 className="display mt-3 text-4xl font-bold">Built to explain, not overwhelm.</h2><div className="mt-9 grid gap-4 md:grid-cols-4">{items.map(([x,y])=><article className="border-t-2 border-sage pt-5" key={x}><h3 className="font-bold text-sm">{x}</h3><p className="mt-3 text-sm leading-6 text-ink/60">{y}</p></article>)}</div></section>}
export function FinalCta(){return <section className="container pb-24"><div className="overflow-hidden rounded-[28px] bg-ink px-7 py-14 text-center text-white sm:px-14"><Sparkles className="mx-auto text-[#b8dac9]"/><h2 className="display mt-5 text-4xl font-bold">Know the process.<br/>Take the next step.</h2><p className="mt-3 text-white/65">LokSeva helps organize public authority routing, required documents, and RTI application drafts.</p></div></section>}

